version: '3.9'
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: krishi
    ports:
      - "5432:5432"
  api:
    build:
      context: ./api
      dockerfile: ../docker/api.Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  web:
    build:
      context: ./web
      dockerfile: ../docker/web.Dockerfile
    env_file: .env
    depends_on:
      - api
    ports:
      - "3000:3000"
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - web
    ports:
      - "80:80"
